CC = g++

OBJS = main.cpp

LIBRARIES = -lSDL3 -lGL -lGLEW

FLAGS = -Wall

OBJ_NAME = 01-Creating-a-Window

all : $(OBJS)
	$(CC) $(OBJS) $(LIBRARIES) $(FLAGS) -o $(OBJ_NAME)

clean :
	rm -f $(OBJ_NAME)
